#############################################################################
# Makefile for building: demo1
# Generated by qmake (3.0) (Qt 5.3.0)
# Project:  demo1.pro
# Template: app
# Command: /home/kakadu/Qt5.2/5.3/gcc/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile demo1.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_DECLARATIVE_LIB -DQT_WIDGETS_LIB -DQT_SCRIPT_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../Qt_off/5.3/gcc/mkspecs/linux-g++ -I. -Iqtquick1applicationviewer -I../../Qt_off/5.3/gcc/include -I../../Qt_off/5.3/gcc/include/QtDeclarative -I../../Qt_off/5.3/gcc/include/QtWidgets -I../../Qt_off/5.3/gcc/include/QtScript -I../../Qt_off/5.3/gcc/include/QtGui -I../../Qt_off/5.3/gcc/include/QtCore -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/kakadu/Qt5.2/5.3/gcc -Wl,-rpath,/home/kakadu/Qt5.2/5.3/gcc/lib -Wl,-rpath-link,/home/kakadu/Qt5.2/5.3/gcc/lib
LIBS          = $(SUBLIBS) -L/home/kakadu/Qt5.2/5.3/gcc/lib -lQt5Declarative -lQt5XmlPatterns -lQt5Network -lQt5Sql -lQt5Widgets -lQt5Script -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/kakadu/Qt5.2/5.3/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		canvas.cpp \
		qtquick1applicationviewer/qtquick1applicationviewer.cpp qrc_qml.cpp \
		moc_qtquick1applicationviewer.cpp \
		moc_canvas.cpp \
		moc_line.cpp
OBJECTS       = main.o \
		canvas.o \
		qtquick1applicationviewer.o \
		qrc_qml.o \
		moc_qtquick1applicationviewer.o \
		moc_canvas.o \
		moc_line.o
DIST          = ../../Qt_off/5.3/gcc/mkspecs/features/spec_pre.prf \
		../../Qt_off/5.3/gcc/mkspecs/common/shell-unix.conf \
		../../Qt_off/5.3/gcc/mkspecs/common/unix.conf \
		../../Qt_off/5.3/gcc/mkspecs/common/linux.conf \
		../../Qt_off/5.3/gcc/mkspecs/common/gcc-base.conf \
		../../Qt_off/5.3/gcc/mkspecs/common/gcc-base-unix.conf \
		../../Qt_off/5.3/gcc/mkspecs/common/g++-base.conf \
		../../Qt_off/5.3/gcc/mkspecs/common/g++-unix.conf \
		../../Qt_off/5.3/gcc/mkspecs/qconfig.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_core.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_designer.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_gui.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_help.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_network.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_qml.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_quick.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_script.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_sql.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_svg.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_xml.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/features/qt_functions.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/qt_config.prf \
		../../Qt_off/5.3/gcc/mkspecs/linux-g++/qmake.conf \
		../../Qt_off/5.3/gcc/mkspecs/features/spec_post.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/exclusive_builds.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/default_pre.prf \
		qtquick1applicationviewer/qtquick1applicationviewer.pri \
		deployment.pri \
		../../Qt_off/5.3/gcc/mkspecs/features/resolve_config.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/default_post.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/qml_debug.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/declarative_debug.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/warn_on.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/qt.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/resources.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/moc.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/unix/opengl.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/uic.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/unix/thread.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/testcase_targets.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/exceptions.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/yacc.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/lex.prf \
		demo1.pro main.cpp \
		canvas.cpp \
		qtquick1applicationviewer/qtquick1applicationviewer.cpp
QMAKE_TARGET  = demo1
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = demo1


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: demo1.pro ../../Qt_off/5.3/gcc/mkspecs/linux-g++/qmake.conf ../../Qt_off/5.3/gcc/mkspecs/features/spec_pre.prf \
		../../Qt_off/5.3/gcc/mkspecs/common/shell-unix.conf \
		../../Qt_off/5.3/gcc/mkspecs/common/unix.conf \
		../../Qt_off/5.3/gcc/mkspecs/common/linux.conf \
		../../Qt_off/5.3/gcc/mkspecs/common/gcc-base.conf \
		../../Qt_off/5.3/gcc/mkspecs/common/gcc-base-unix.conf \
		../../Qt_off/5.3/gcc/mkspecs/common/g++-base.conf \
		../../Qt_off/5.3/gcc/mkspecs/common/g++-unix.conf \
		../../Qt_off/5.3/gcc/mkspecs/qconfig.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_core.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_designer.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_gui.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_help.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_network.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_qml.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_quick.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_script.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_sql.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_svg.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_xml.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt_off/5.3/gcc/mkspecs/features/qt_functions.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/qt_config.prf \
		../../Qt_off/5.3/gcc/mkspecs/linux-g++/qmake.conf \
		../../Qt_off/5.3/gcc/mkspecs/features/spec_post.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/exclusive_builds.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/default_pre.prf \
		qtquick1applicationviewer/qtquick1applicationviewer.pri \
		deployment.pri \
		../../Qt_off/5.3/gcc/mkspecs/features/resolve_config.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/default_post.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/qml_debug.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/declarative_debug.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/warn_on.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/qt.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/resources.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/moc.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/unix/opengl.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/uic.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/unix/thread.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/testcase_targets.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/exceptions.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/yacc.prf \
		../../Qt_off/5.3/gcc/mkspecs/features/lex.prf \
		demo1.pro \
		qml.qrc \
		/home/kakadu/Qt5.2/5.3/gcc/lib/libQt5Declarative.prl \
		/home/kakadu/Qt5.2/5.3/gcc/lib/libQt5XmlPatterns.prl \
		/home/kakadu/Qt5.2/5.3/gcc/lib/libQt5Network.prl \
		/home/kakadu/Qt5.2/5.3/gcc/lib/libQt5Core.prl \
		/home/kakadu/Qt5.2/5.3/gcc/lib/libQt5Widgets.prl \
		/home/kakadu/Qt5.2/5.3/gcc/lib/libQt5Gui.prl \
		/home/kakadu/Qt5.2/5.3/gcc/lib/libQt5Sql.prl \
		/home/kakadu/Qt5.2/5.3/gcc/lib/libQt5Script.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile demo1.pro
../../Qt_off/5.3/gcc/mkspecs/features/spec_pre.prf:
../../Qt_off/5.3/gcc/mkspecs/common/shell-unix.conf:
../../Qt_off/5.3/gcc/mkspecs/common/unix.conf:
../../Qt_off/5.3/gcc/mkspecs/common/linux.conf:
../../Qt_off/5.3/gcc/mkspecs/common/gcc-base.conf:
../../Qt_off/5.3/gcc/mkspecs/common/gcc-base-unix.conf:
../../Qt_off/5.3/gcc/mkspecs/common/g++-base.conf:
../../Qt_off/5.3/gcc/mkspecs/common/g++-unix.conf:
../../Qt_off/5.3/gcc/mkspecs/qconfig.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_core.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_core_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_dbus.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_declarative.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_designer.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_enginio.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_enginio_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_gui.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_help.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_help_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_network.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_network_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_nfc.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_opengl.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_positioning.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_qml.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_quick.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_script.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_script_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_sensors.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_serialport.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_sql.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_svg.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_testlib.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_uitools.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_webkit.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_websockets.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_widgets.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_x11extras.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_xml.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt_off/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt_off/5.3/gcc/mkspecs/features/qt_functions.prf:
../../Qt_off/5.3/gcc/mkspecs/features/qt_config.prf:
../../Qt_off/5.3/gcc/mkspecs/linux-g++/qmake.conf:
../../Qt_off/5.3/gcc/mkspecs/features/spec_post.prf:
../../Qt_off/5.3/gcc/mkspecs/features/exclusive_builds.prf:
../../Qt_off/5.3/gcc/mkspecs/features/default_pre.prf:
qtquick1applicationviewer/qtquick1applicationviewer.pri:
deployment.pri:
../../Qt_off/5.3/gcc/mkspecs/features/resolve_config.prf:
../../Qt_off/5.3/gcc/mkspecs/features/default_post.prf:
../../Qt_off/5.3/gcc/mkspecs/features/qml_debug.prf:
../../Qt_off/5.3/gcc/mkspecs/features/declarative_debug.prf:
../../Qt_off/5.3/gcc/mkspecs/features/warn_on.prf:
../../Qt_off/5.3/gcc/mkspecs/features/qt.prf:
../../Qt_off/5.3/gcc/mkspecs/features/resources.prf:
../../Qt_off/5.3/gcc/mkspecs/features/moc.prf:
../../Qt_off/5.3/gcc/mkspecs/features/unix/opengl.prf:
../../Qt_off/5.3/gcc/mkspecs/features/uic.prf:
../../Qt_off/5.3/gcc/mkspecs/features/unix/thread.prf:
../../Qt_off/5.3/gcc/mkspecs/features/testcase_targets.prf:
../../Qt_off/5.3/gcc/mkspecs/features/exceptions.prf:
../../Qt_off/5.3/gcc/mkspecs/features/yacc.prf:
../../Qt_off/5.3/gcc/mkspecs/features/lex.prf:
demo1.pro:
qml.qrc:
/home/kakadu/Qt5.2/5.3/gcc/lib/libQt5Declarative.prl:
/home/kakadu/Qt5.2/5.3/gcc/lib/libQt5XmlPatterns.prl:
/home/kakadu/Qt5.2/5.3/gcc/lib/libQt5Network.prl:
/home/kakadu/Qt5.2/5.3/gcc/lib/libQt5Core.prl:
/home/kakadu/Qt5.2/5.3/gcc/lib/libQt5Widgets.prl:
/home/kakadu/Qt5.2/5.3/gcc/lib/libQt5Gui.prl:
/home/kakadu/Qt5.2/5.3/gcc/lib/libQt5Sql.prl:
/home/kakadu/Qt5.2/5.3/gcc/lib/libQt5Script.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile demo1.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/demo11.0.0 || mkdir -p .tmp/demo11.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/demo11.0.0/ && $(COPY_FILE) --parents qml.qrc .tmp/demo11.0.0/ && $(COPY_FILE) --parents qtquick1applicationviewer/qtquick1applicationviewer.h canvas.h line.h .tmp/demo11.0.0/ && $(COPY_FILE) --parents main.cpp canvas.cpp qtquick1applicationviewer/qtquick1applicationviewer.cpp .tmp/demo11.0.0/ && (cd `dirname .tmp/demo11.0.0` && $(TAR) demo11.0.0.tar demo11.0.0 && $(COMPRESS) demo11.0.0.tar) && $(MOVE) `dirname .tmp/demo11.0.0`/demo11.0.0.tar.gz . && $(DEL_FILE) -r .tmp/demo11.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		main.qml
	/home/kakadu/Qt5.2/5.3/gcc/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all: moc_qtquick1applicationviewer.cpp moc_canvas.cpp moc_line.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qtquick1applicationviewer.cpp moc_canvas.cpp moc_line.cpp
moc_qtquick1applicationviewer.cpp: ../../Qt_off/5.3/gcc/include/QtDeclarative/QDeclarativeView \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeview.h \
		../../Qt_off/5.3/gcc/include/QtCore/qdatetime.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstring.h \
		../../Qt_off/5.3/gcc/include/QtCore/qchar.h \
		../../Qt_off/5.3/gcc/include/QtCore/qglobal.h \
		../../Qt_off/5.3/gcc/include/QtCore/qconfig.h \
		../../Qt_off/5.3/gcc/include/QtCore/qfeatures.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsystemdetection.h \
		../../Qt_off/5.3/gcc/include/QtCore/qprocessordetection.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt_off/5.3/gcc/include/QtCore/qtypeinfo.h \
		../../Qt_off/5.3/gcc/include/QtCore/qtypetraits.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsysinfo.h \
		../../Qt_off/5.3/gcc/include/QtCore/qlogging.h \
		../../Qt_off/5.3/gcc/include/QtCore/qflags.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qbasicatomic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt_off/5.3/gcc/include/QtCore/qgenericatomic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_mips.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_x86.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_unix.h \
		../../Qt_off/5.3/gcc/include/QtCore/qglobalstatic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmutex.h \
		../../Qt_off/5.3/gcc/include/QtCore/qnumeric.h \
		../../Qt_off/5.3/gcc/include/QtCore/qbytearray.h \
		../../Qt_off/5.3/gcc/include/QtCore/qrefcount.h \
		../../Qt_off/5.3/gcc/include/QtCore/qnamespace.h \
		../../Qt_off/5.3/gcc/include/QtCore/qarraydata.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstringbuilder.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsharedpointer.h \
		../../Qt_off/5.3/gcc/include/QtCore/qshareddata.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobject.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobjectdefs.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt_off/5.3/gcc/include/QtCore/qlist.h \
		../../Qt_off/5.3/gcc/include/QtCore/qalgorithms.h \
		../../Qt_off/5.3/gcc/include/QtCore/qiterator.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcoreevent.h \
		../../Qt_off/5.3/gcc/include/QtCore/qscopedpointer.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmetatype.h \
		../../Qt_off/5.3/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt_off/5.3/gcc/include/QtCore/qisenum.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobject_impl.h \
		../../Qt_off/5.3/gcc/include/QtCore/qhash.h \
		../../Qt_off/5.3/gcc/include/QtCore/qpair.h \
		../../Qt_off/5.3/gcc/include/QtCore/qurl.h \
		../../Qt_off/5.3/gcc/include/QtCore/qurlquery.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstringlist.h \
		../../Qt_off/5.3/gcc/include/QtCore/qdatastream.h \
		../../Qt_off/5.3/gcc/include/QtCore/qiodevice.h \
		../../Qt_off/5.3/gcc/include/QtCore/qregexp.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstringmatcher.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicssceneevent.h \
		../../Qt_off/5.3/gcc/include/QtCore/qpoint.h \
		../../Qt_off/5.3/gcc/include/QtCore/qrect.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmargins.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsize.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpolygon.h \
		../../Qt_off/5.3/gcc/include/QtCore/qvector.h \
		../../Qt_off/5.3/gcc/include/QtCore/qset.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicsview.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpainter.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpixmap.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpaintdevice.h \
		../../Qt_off/5.3/gcc/include/QtGui/qwindowdefs.h \
		../../Qt_off/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		../../Qt_off/5.3/gcc/include/QtGui/qcolor.h \
		../../Qt_off/5.3/gcc/include/QtGui/qrgb.h \
		../../Qt_off/5.3/gcc/include/QtGui/qimage.h \
		../../Qt_off/5.3/gcc/include/QtGui/qtransform.h \
		../../Qt_off/5.3/gcc/include/QtGui/qmatrix.h \
		../../Qt_off/5.3/gcc/include/QtGui/qregion.h \
		../../Qt_off/5.3/gcc/include/QtCore/qline.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpainterpath.h \
		../../Qt_off/5.3/gcc/include/QtGui/qtextoption.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpen.h \
		../../Qt_off/5.3/gcc/include/QtGui/qbrush.h \
		../../Qt_off/5.3/gcc/include/QtGui/qfontinfo.h \
		../../Qt_off/5.3/gcc/include/QtGui/qfont.h \
		../../Qt_off/5.3/gcc/include/QtGui/qfontmetrics.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qscrollarea.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qabstractscrollarea.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qframe.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qwidget.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpalette.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		../../Qt_off/5.3/gcc/include/QtGui/qcursor.h \
		../../Qt_off/5.3/gcc/include/QtGui/qkeysequence.h \
		../../Qt_off/5.3/gcc/include/QtGui/qevent.h \
		../../Qt_off/5.3/gcc/include/QtCore/qvariant.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmap.h \
		../../Qt_off/5.3/gcc/include/QtCore/qdebug.h \
		../../Qt_off/5.3/gcc/include/QtCore/qtextstream.h \
		../../Qt_off/5.3/gcc/include/QtCore/qlocale.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt_off/5.3/gcc/include/QtCore/qfile.h \
		../../Qt_off/5.3/gcc/include/QtCore/qfiledevice.h \
		../../Qt_off/5.3/gcc/include/QtGui/qvector2d.h \
		../../Qt_off/5.3/gcc/include/QtGui/qtouchdevice.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicsscene.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativedebug.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qtdeclarativeglobal.h \
		qtquick1applicationviewer/qtquick1applicationviewer.h
	/home/kakadu/Qt5.2/5.3/gcc/bin/moc $(DEFINES) -I/home/kakadu/Qt5.2/5.3/gcc/mkspecs/linux-g++ -I/home/kakadu/qtDeclTest/demo1 -I/home/kakadu/qtDeclTest/demo1/qtquick1applicationviewer -I/home/kakadu/Qt5.2/5.3/gcc/include -I/home/kakadu/Qt5.2/5.3/gcc/include/QtDeclarative -I/home/kakadu/Qt5.2/5.3/gcc/include/QtWidgets -I/home/kakadu/Qt5.2/5.3/gcc/include/QtScript -I/home/kakadu/Qt5.2/5.3/gcc/include/QtGui -I/home/kakadu/Qt5.2/5.3/gcc/include/QtCore qtquick1applicationviewer/qtquick1applicationviewer.h -o moc_qtquick1applicationviewer.cpp

moc_canvas.cpp: ../../Qt_off/5.3/gcc/include/QtDeclarative/QDeclarativeItem \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeitem.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarative.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeprivate.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qtdeclarativeglobal.h \
		../../Qt_off/5.3/gcc/include/QtCore/qglobal.h \
		../../Qt_off/5.3/gcc/include/QtCore/qconfig.h \
		../../Qt_off/5.3/gcc/include/QtCore/qfeatures.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsystemdetection.h \
		../../Qt_off/5.3/gcc/include/QtCore/qprocessordetection.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt_off/5.3/gcc/include/QtCore/qtypeinfo.h \
		../../Qt_off/5.3/gcc/include/QtCore/qtypetraits.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsysinfo.h \
		../../Qt_off/5.3/gcc/include/QtCore/qlogging.h \
		../../Qt_off/5.3/gcc/include/QtCore/qflags.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qbasicatomic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt_off/5.3/gcc/include/QtCore/qgenericatomic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_mips.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_x86.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_unix.h \
		../../Qt_off/5.3/gcc/include/QtCore/qglobalstatic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmutex.h \
		../../Qt_off/5.3/gcc/include/QtCore/qnumeric.h \
		../../Qt_off/5.3/gcc/include/QtCore/qvariant.h \
		../../Qt_off/5.3/gcc/include/QtCore/qbytearray.h \
		../../Qt_off/5.3/gcc/include/QtCore/qrefcount.h \
		../../Qt_off/5.3/gcc/include/QtCore/qnamespace.h \
		../../Qt_off/5.3/gcc/include/QtCore/qarraydata.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstring.h \
		../../Qt_off/5.3/gcc/include/QtCore/qchar.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstringbuilder.h \
		../../Qt_off/5.3/gcc/include/QtCore/qlist.h \
		../../Qt_off/5.3/gcc/include/QtCore/qalgorithms.h \
		../../Qt_off/5.3/gcc/include/QtCore/qiterator.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmetatype.h \
		../../Qt_off/5.3/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt_off/5.3/gcc/include/QtCore/qisenum.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobjectdefs.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmap.h \
		../../Qt_off/5.3/gcc/include/QtCore/qpair.h \
		../../Qt_off/5.3/gcc/include/QtCore/qdebug.h \
		../../Qt_off/5.3/gcc/include/QtCore/qhash.h \
		../../Qt_off/5.3/gcc/include/QtCore/qtextstream.h \
		../../Qt_off/5.3/gcc/include/QtCore/qiodevice.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobject.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcoreevent.h \
		../../Qt_off/5.3/gcc/include/QtCore/qscopedpointer.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobject_impl.h \
		../../Qt_off/5.3/gcc/include/QtCore/qlocale.h \
		../../Qt_off/5.3/gcc/include/QtCore/qshareddata.h \
		../../Qt_off/5.3/gcc/include/QtCore/qvector.h \
		../../Qt_off/5.3/gcc/include/QtCore/qpoint.h \
		../../Qt_off/5.3/gcc/include/QtCore/qset.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstringlist.h \
		../../Qt_off/5.3/gcc/include/QtCore/qdatastream.h \
		../../Qt_off/5.3/gcc/include/QtCore/qregexp.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstringmatcher.h \
		../../Qt_off/5.3/gcc/include/QtCore/qurl.h \
		../../Qt_off/5.3/gcc/include/QtCore/qurlquery.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeparserstatus.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativepropertyvaluesource.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativepropertyvalueinterceptor.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativelist.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmetaobject.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativecomponent.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeerror.h \
		../../Qt_off/5.3/gcc/include/QtScript/qscriptvalue.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsharedpointer.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt_off/5.3/gcc/include/QtScript/qtscriptglobal.h \
		../../Qt_off/5.3/gcc/include/QtCore/QObject \
		../../Qt_off/5.3/gcc/include/QtCore/QList \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicstransform.h \
		../../Qt_off/5.3/gcc/include/QtGui/QVector3D \
		../../Qt_off/5.3/gcc/include/QtGui/qvector3d.h \
		../../Qt_off/5.3/gcc/include/QtGui/QTransform \
		../../Qt_off/5.3/gcc/include/QtGui/qtransform.h \
		../../Qt_off/5.3/gcc/include/QtGui/qmatrix.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpolygon.h \
		../../Qt_off/5.3/gcc/include/QtCore/qrect.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmargins.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsize.h \
		../../Qt_off/5.3/gcc/include/QtGui/qregion.h \
		../../Qt_off/5.3/gcc/include/QtGui/qwindowdefs.h \
		../../Qt_off/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		../../Qt_off/5.3/gcc/include/QtCore/qline.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpainterpath.h \
		../../Qt_off/5.3/gcc/include/QtGui/QMatrix4x4 \
		../../Qt_off/5.3/gcc/include/QtGui/qmatrix4x4.h \
		../../Qt_off/5.3/gcc/include/QtGui/qvector4d.h \
		../../Qt_off/5.3/gcc/include/QtGui/qquaternion.h \
		../../Qt_off/5.3/gcc/include/QtGui/qgenericmatrix.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicswidget.h \
		../../Qt_off/5.3/gcc/include/QtGui/qfont.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicslayoutitem.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		../../Qt_off/5.3/gcc/include/QtGui/qevent.h \
		../../Qt_off/5.3/gcc/include/QtGui/qkeysequence.h \
		../../Qt_off/5.3/gcc/include/QtCore/qfile.h \
		../../Qt_off/5.3/gcc/include/QtCore/qfiledevice.h \
		../../Qt_off/5.3/gcc/include/QtGui/qvector2d.h \
		../../Qt_off/5.3/gcc/include/QtGui/qtouchdevice.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicsitem.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpixmap.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpaintdevice.h \
		../../Qt_off/5.3/gcc/include/QtGui/qcolor.h \
		../../Qt_off/5.3/gcc/include/QtGui/qrgb.h \
		../../Qt_off/5.3/gcc/include/QtGui/qimage.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpalette.h \
		../../Qt_off/5.3/gcc/include/QtGui/qbrush.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qaction.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qwidget.h \
		../../Qt_off/5.3/gcc/include/QtGui/qfontmetrics.h \
		../../Qt_off/5.3/gcc/include/QtGui/qfontinfo.h \
		../../Qt_off/5.3/gcc/include/QtGui/qcursor.h \
		../../Qt_off/5.3/gcc/include/QtGui/qicon.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qactiongroup.h \
		canvas.h
	/home/kakadu/Qt5.2/5.3/gcc/bin/moc $(DEFINES) -I/home/kakadu/Qt5.2/5.3/gcc/mkspecs/linux-g++ -I/home/kakadu/qtDeclTest/demo1 -I/home/kakadu/qtDeclTest/demo1/qtquick1applicationviewer -I/home/kakadu/Qt5.2/5.3/gcc/include -I/home/kakadu/Qt5.2/5.3/gcc/include/QtDeclarative -I/home/kakadu/Qt5.2/5.3/gcc/include/QtWidgets -I/home/kakadu/Qt5.2/5.3/gcc/include/QtScript -I/home/kakadu/Qt5.2/5.3/gcc/include/QtGui -I/home/kakadu/Qt5.2/5.3/gcc/include/QtCore canvas.h -o moc_canvas.cpp

moc_line.cpp: ../../Qt_off/5.3/gcc/include/QtDeclarative/QDeclarativeItem \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeitem.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarative.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeprivate.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qtdeclarativeglobal.h \
		../../Qt_off/5.3/gcc/include/QtCore/qglobal.h \
		../../Qt_off/5.3/gcc/include/QtCore/qconfig.h \
		../../Qt_off/5.3/gcc/include/QtCore/qfeatures.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsystemdetection.h \
		../../Qt_off/5.3/gcc/include/QtCore/qprocessordetection.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt_off/5.3/gcc/include/QtCore/qtypeinfo.h \
		../../Qt_off/5.3/gcc/include/QtCore/qtypetraits.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsysinfo.h \
		../../Qt_off/5.3/gcc/include/QtCore/qlogging.h \
		../../Qt_off/5.3/gcc/include/QtCore/qflags.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qbasicatomic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt_off/5.3/gcc/include/QtCore/qgenericatomic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_mips.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_x86.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_unix.h \
		../../Qt_off/5.3/gcc/include/QtCore/qglobalstatic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmutex.h \
		../../Qt_off/5.3/gcc/include/QtCore/qnumeric.h \
		../../Qt_off/5.3/gcc/include/QtCore/qvariant.h \
		../../Qt_off/5.3/gcc/include/QtCore/qbytearray.h \
		../../Qt_off/5.3/gcc/include/QtCore/qrefcount.h \
		../../Qt_off/5.3/gcc/include/QtCore/qnamespace.h \
		../../Qt_off/5.3/gcc/include/QtCore/qarraydata.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstring.h \
		../../Qt_off/5.3/gcc/include/QtCore/qchar.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstringbuilder.h \
		../../Qt_off/5.3/gcc/include/QtCore/qlist.h \
		../../Qt_off/5.3/gcc/include/QtCore/qalgorithms.h \
		../../Qt_off/5.3/gcc/include/QtCore/qiterator.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmetatype.h \
		../../Qt_off/5.3/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt_off/5.3/gcc/include/QtCore/qisenum.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobjectdefs.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmap.h \
		../../Qt_off/5.3/gcc/include/QtCore/qpair.h \
		../../Qt_off/5.3/gcc/include/QtCore/qdebug.h \
		../../Qt_off/5.3/gcc/include/QtCore/qhash.h \
		../../Qt_off/5.3/gcc/include/QtCore/qtextstream.h \
		../../Qt_off/5.3/gcc/include/QtCore/qiodevice.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobject.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcoreevent.h \
		../../Qt_off/5.3/gcc/include/QtCore/qscopedpointer.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobject_impl.h \
		../../Qt_off/5.3/gcc/include/QtCore/qlocale.h \
		../../Qt_off/5.3/gcc/include/QtCore/qshareddata.h \
		../../Qt_off/5.3/gcc/include/QtCore/qvector.h \
		../../Qt_off/5.3/gcc/include/QtCore/qpoint.h \
		../../Qt_off/5.3/gcc/include/QtCore/qset.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstringlist.h \
		../../Qt_off/5.3/gcc/include/QtCore/qdatastream.h \
		../../Qt_off/5.3/gcc/include/QtCore/qregexp.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstringmatcher.h \
		../../Qt_off/5.3/gcc/include/QtCore/qurl.h \
		../../Qt_off/5.3/gcc/include/QtCore/qurlquery.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeparserstatus.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativepropertyvaluesource.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativepropertyvalueinterceptor.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativelist.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmetaobject.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativecomponent.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeerror.h \
		../../Qt_off/5.3/gcc/include/QtScript/qscriptvalue.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsharedpointer.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt_off/5.3/gcc/include/QtScript/qtscriptglobal.h \
		../../Qt_off/5.3/gcc/include/QtCore/QObject \
		../../Qt_off/5.3/gcc/include/QtCore/QList \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicstransform.h \
		../../Qt_off/5.3/gcc/include/QtGui/QVector3D \
		../../Qt_off/5.3/gcc/include/QtGui/qvector3d.h \
		../../Qt_off/5.3/gcc/include/QtGui/QTransform \
		../../Qt_off/5.3/gcc/include/QtGui/qtransform.h \
		../../Qt_off/5.3/gcc/include/QtGui/qmatrix.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpolygon.h \
		../../Qt_off/5.3/gcc/include/QtCore/qrect.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmargins.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsize.h \
		../../Qt_off/5.3/gcc/include/QtGui/qregion.h \
		../../Qt_off/5.3/gcc/include/QtGui/qwindowdefs.h \
		../../Qt_off/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		../../Qt_off/5.3/gcc/include/QtCore/qline.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpainterpath.h \
		../../Qt_off/5.3/gcc/include/QtGui/QMatrix4x4 \
		../../Qt_off/5.3/gcc/include/QtGui/qmatrix4x4.h \
		../../Qt_off/5.3/gcc/include/QtGui/qvector4d.h \
		../../Qt_off/5.3/gcc/include/QtGui/qquaternion.h \
		../../Qt_off/5.3/gcc/include/QtGui/qgenericmatrix.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicswidget.h \
		../../Qt_off/5.3/gcc/include/QtGui/qfont.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicslayoutitem.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		../../Qt_off/5.3/gcc/include/QtGui/qevent.h \
		../../Qt_off/5.3/gcc/include/QtGui/qkeysequence.h \
		../../Qt_off/5.3/gcc/include/QtCore/qfile.h \
		../../Qt_off/5.3/gcc/include/QtCore/qfiledevice.h \
		../../Qt_off/5.3/gcc/include/QtGui/qvector2d.h \
		../../Qt_off/5.3/gcc/include/QtGui/qtouchdevice.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicsitem.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpixmap.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpaintdevice.h \
		../../Qt_off/5.3/gcc/include/QtGui/qcolor.h \
		../../Qt_off/5.3/gcc/include/QtGui/qrgb.h \
		../../Qt_off/5.3/gcc/include/QtGui/qimage.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpalette.h \
		../../Qt_off/5.3/gcc/include/QtGui/qbrush.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qaction.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qwidget.h \
		../../Qt_off/5.3/gcc/include/QtGui/qfontmetrics.h \
		../../Qt_off/5.3/gcc/include/QtGui/qfontinfo.h \
		../../Qt_off/5.3/gcc/include/QtGui/qcursor.h \
		../../Qt_off/5.3/gcc/include/QtGui/qicon.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qactiongroup.h \
		../../Qt_off/5.3/gcc/include/QtGui/QPainter \
		../../Qt_off/5.3/gcc/include/QtGui/qpainter.h \
		../../Qt_off/5.3/gcc/include/QtGui/qtextoption.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpen.h \
		line.h
	/home/kakadu/Qt5.2/5.3/gcc/bin/moc $(DEFINES) -I/home/kakadu/Qt5.2/5.3/gcc/mkspecs/linux-g++ -I/home/kakadu/qtDeclTest/demo1 -I/home/kakadu/qtDeclTest/demo1/qtquick1applicationviewer -I/home/kakadu/Qt5.2/5.3/gcc/include -I/home/kakadu/Qt5.2/5.3/gcc/include/QtDeclarative -I/home/kakadu/Qt5.2/5.3/gcc/include/QtWidgets -I/home/kakadu/Qt5.2/5.3/gcc/include/QtScript -I/home/kakadu/Qt5.2/5.3/gcc/include/QtGui -I/home/kakadu/Qt5.2/5.3/gcc/include/QtCore line.h -o moc_line.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp qtquick1applicationviewer/qtquick1applicationviewer.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/QDeclarativeView \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeview.h \
		../../Qt_off/5.3/gcc/include/QtCore/qdatetime.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstring.h \
		../../Qt_off/5.3/gcc/include/QtCore/qchar.h \
		../../Qt_off/5.3/gcc/include/QtCore/qglobal.h \
		../../Qt_off/5.3/gcc/include/QtCore/qconfig.h \
		../../Qt_off/5.3/gcc/include/QtCore/qfeatures.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsystemdetection.h \
		../../Qt_off/5.3/gcc/include/QtCore/qprocessordetection.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt_off/5.3/gcc/include/QtCore/qtypeinfo.h \
		../../Qt_off/5.3/gcc/include/QtCore/qtypetraits.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsysinfo.h \
		../../Qt_off/5.3/gcc/include/QtCore/qlogging.h \
		../../Qt_off/5.3/gcc/include/QtCore/qflags.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qbasicatomic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt_off/5.3/gcc/include/QtCore/qgenericatomic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_mips.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_x86.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_unix.h \
		../../Qt_off/5.3/gcc/include/QtCore/qglobalstatic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmutex.h \
		../../Qt_off/5.3/gcc/include/QtCore/qnumeric.h \
		../../Qt_off/5.3/gcc/include/QtCore/qbytearray.h \
		../../Qt_off/5.3/gcc/include/QtCore/qrefcount.h \
		../../Qt_off/5.3/gcc/include/QtCore/qnamespace.h \
		../../Qt_off/5.3/gcc/include/QtCore/qarraydata.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstringbuilder.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsharedpointer.h \
		../../Qt_off/5.3/gcc/include/QtCore/qshareddata.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobject.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobjectdefs.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt_off/5.3/gcc/include/QtCore/qlist.h \
		../../Qt_off/5.3/gcc/include/QtCore/qalgorithms.h \
		../../Qt_off/5.3/gcc/include/QtCore/qiterator.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcoreevent.h \
		../../Qt_off/5.3/gcc/include/QtCore/qscopedpointer.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmetatype.h \
		../../Qt_off/5.3/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt_off/5.3/gcc/include/QtCore/qisenum.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobject_impl.h \
		../../Qt_off/5.3/gcc/include/QtCore/qhash.h \
		../../Qt_off/5.3/gcc/include/QtCore/qpair.h \
		../../Qt_off/5.3/gcc/include/QtCore/qurl.h \
		../../Qt_off/5.3/gcc/include/QtCore/qurlquery.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstringlist.h \
		../../Qt_off/5.3/gcc/include/QtCore/qdatastream.h \
		../../Qt_off/5.3/gcc/include/QtCore/qiodevice.h \
		../../Qt_off/5.3/gcc/include/QtCore/qregexp.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstringmatcher.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicssceneevent.h \
		../../Qt_off/5.3/gcc/include/QtCore/qpoint.h \
		../../Qt_off/5.3/gcc/include/QtCore/qrect.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmargins.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsize.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpolygon.h \
		../../Qt_off/5.3/gcc/include/QtCore/qvector.h \
		../../Qt_off/5.3/gcc/include/QtCore/qset.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicsview.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpainter.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpixmap.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpaintdevice.h \
		../../Qt_off/5.3/gcc/include/QtGui/qwindowdefs.h \
		../../Qt_off/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		../../Qt_off/5.3/gcc/include/QtGui/qcolor.h \
		../../Qt_off/5.3/gcc/include/QtGui/qrgb.h \
		../../Qt_off/5.3/gcc/include/QtGui/qimage.h \
		../../Qt_off/5.3/gcc/include/QtGui/qtransform.h \
		../../Qt_off/5.3/gcc/include/QtGui/qmatrix.h \
		../../Qt_off/5.3/gcc/include/QtGui/qregion.h \
		../../Qt_off/5.3/gcc/include/QtCore/qline.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpainterpath.h \
		../../Qt_off/5.3/gcc/include/QtGui/qtextoption.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpen.h \
		../../Qt_off/5.3/gcc/include/QtGui/qbrush.h \
		../../Qt_off/5.3/gcc/include/QtGui/qfontinfo.h \
		../../Qt_off/5.3/gcc/include/QtGui/qfont.h \
		../../Qt_off/5.3/gcc/include/QtGui/qfontmetrics.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qscrollarea.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qabstractscrollarea.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qframe.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qwidget.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpalette.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		../../Qt_off/5.3/gcc/include/QtGui/qcursor.h \
		../../Qt_off/5.3/gcc/include/QtGui/qkeysequence.h \
		../../Qt_off/5.3/gcc/include/QtGui/qevent.h \
		../../Qt_off/5.3/gcc/include/QtCore/qvariant.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmap.h \
		../../Qt_off/5.3/gcc/include/QtCore/qdebug.h \
		../../Qt_off/5.3/gcc/include/QtCore/qtextstream.h \
		../../Qt_off/5.3/gcc/include/QtCore/qlocale.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt_off/5.3/gcc/include/QtCore/qfile.h \
		../../Qt_off/5.3/gcc/include/QtCore/qfiledevice.h \
		../../Qt_off/5.3/gcc/include/QtGui/qvector2d.h \
		../../Qt_off/5.3/gcc/include/QtGui/qtouchdevice.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicsscene.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativedebug.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qtdeclarativeglobal.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/QApplication \
		../../Qt_off/5.3/gcc/include/QtWidgets/qapplication.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcoreapplication.h \
		../../Qt_off/5.3/gcc/include/QtCore/qeventloop.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qdesktopwidget.h \
		../../Qt_off/5.3/gcc/include/QtGui/qguiapplication.h \
		../../Qt_off/5.3/gcc/include/QtGui/qinputmethod.h \
		canvas.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/QDeclarativeItem \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeitem.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarative.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeprivate.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeparserstatus.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativepropertyvaluesource.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativepropertyvalueinterceptor.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativelist.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmetaobject.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativecomponent.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeerror.h \
		../../Qt_off/5.3/gcc/include/QtScript/qscriptvalue.h \
		../../Qt_off/5.3/gcc/include/QtScript/qtscriptglobal.h \
		../../Qt_off/5.3/gcc/include/QtCore/QObject \
		../../Qt_off/5.3/gcc/include/QtCore/QList \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicstransform.h \
		../../Qt_off/5.3/gcc/include/QtGui/QVector3D \
		../../Qt_off/5.3/gcc/include/QtGui/qvector3d.h \
		../../Qt_off/5.3/gcc/include/QtGui/QTransform \
		../../Qt_off/5.3/gcc/include/QtGui/QMatrix4x4 \
		../../Qt_off/5.3/gcc/include/QtGui/qmatrix4x4.h \
		../../Qt_off/5.3/gcc/include/QtGui/qvector4d.h \
		../../Qt_off/5.3/gcc/include/QtGui/qquaternion.h \
		../../Qt_off/5.3/gcc/include/QtGui/qgenericmatrix.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicswidget.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicslayoutitem.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicsitem.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qaction.h \
		../../Qt_off/5.3/gcc/include/QtGui/qicon.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qactiongroup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

canvas.o: canvas.cpp canvas.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/QDeclarativeItem \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeitem.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarative.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeprivate.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qtdeclarativeglobal.h \
		../../Qt_off/5.3/gcc/include/QtCore/qglobal.h \
		../../Qt_off/5.3/gcc/include/QtCore/qconfig.h \
		../../Qt_off/5.3/gcc/include/QtCore/qfeatures.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsystemdetection.h \
		../../Qt_off/5.3/gcc/include/QtCore/qprocessordetection.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt_off/5.3/gcc/include/QtCore/qtypeinfo.h \
		../../Qt_off/5.3/gcc/include/QtCore/qtypetraits.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsysinfo.h \
		../../Qt_off/5.3/gcc/include/QtCore/qlogging.h \
		../../Qt_off/5.3/gcc/include/QtCore/qflags.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qbasicatomic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt_off/5.3/gcc/include/QtCore/qgenericatomic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_mips.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_x86.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_unix.h \
		../../Qt_off/5.3/gcc/include/QtCore/qglobalstatic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmutex.h \
		../../Qt_off/5.3/gcc/include/QtCore/qnumeric.h \
		../../Qt_off/5.3/gcc/include/QtCore/qvariant.h \
		../../Qt_off/5.3/gcc/include/QtCore/qbytearray.h \
		../../Qt_off/5.3/gcc/include/QtCore/qrefcount.h \
		../../Qt_off/5.3/gcc/include/QtCore/qnamespace.h \
		../../Qt_off/5.3/gcc/include/QtCore/qarraydata.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstring.h \
		../../Qt_off/5.3/gcc/include/QtCore/qchar.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstringbuilder.h \
		../../Qt_off/5.3/gcc/include/QtCore/qlist.h \
		../../Qt_off/5.3/gcc/include/QtCore/qalgorithms.h \
		../../Qt_off/5.3/gcc/include/QtCore/qiterator.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmetatype.h \
		../../Qt_off/5.3/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt_off/5.3/gcc/include/QtCore/qisenum.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobjectdefs.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmap.h \
		../../Qt_off/5.3/gcc/include/QtCore/qpair.h \
		../../Qt_off/5.3/gcc/include/QtCore/qdebug.h \
		../../Qt_off/5.3/gcc/include/QtCore/qhash.h \
		../../Qt_off/5.3/gcc/include/QtCore/qtextstream.h \
		../../Qt_off/5.3/gcc/include/QtCore/qiodevice.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobject.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcoreevent.h \
		../../Qt_off/5.3/gcc/include/QtCore/qscopedpointer.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobject_impl.h \
		../../Qt_off/5.3/gcc/include/QtCore/qlocale.h \
		../../Qt_off/5.3/gcc/include/QtCore/qshareddata.h \
		../../Qt_off/5.3/gcc/include/QtCore/qvector.h \
		../../Qt_off/5.3/gcc/include/QtCore/qpoint.h \
		../../Qt_off/5.3/gcc/include/QtCore/qset.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstringlist.h \
		../../Qt_off/5.3/gcc/include/QtCore/qdatastream.h \
		../../Qt_off/5.3/gcc/include/QtCore/qregexp.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstringmatcher.h \
		../../Qt_off/5.3/gcc/include/QtCore/qurl.h \
		../../Qt_off/5.3/gcc/include/QtCore/qurlquery.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeparserstatus.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativepropertyvaluesource.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativepropertyvalueinterceptor.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativelist.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmetaobject.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativecomponent.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeerror.h \
		../../Qt_off/5.3/gcc/include/QtScript/qscriptvalue.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsharedpointer.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt_off/5.3/gcc/include/QtScript/qtscriptglobal.h \
		../../Qt_off/5.3/gcc/include/QtCore/QObject \
		../../Qt_off/5.3/gcc/include/QtCore/QList \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicstransform.h \
		../../Qt_off/5.3/gcc/include/QtGui/QVector3D \
		../../Qt_off/5.3/gcc/include/QtGui/qvector3d.h \
		../../Qt_off/5.3/gcc/include/QtGui/QTransform \
		../../Qt_off/5.3/gcc/include/QtGui/qtransform.h \
		../../Qt_off/5.3/gcc/include/QtGui/qmatrix.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpolygon.h \
		../../Qt_off/5.3/gcc/include/QtCore/qrect.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmargins.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsize.h \
		../../Qt_off/5.3/gcc/include/QtGui/qregion.h \
		../../Qt_off/5.3/gcc/include/QtGui/qwindowdefs.h \
		../../Qt_off/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		../../Qt_off/5.3/gcc/include/QtCore/qline.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpainterpath.h \
		../../Qt_off/5.3/gcc/include/QtGui/QMatrix4x4 \
		../../Qt_off/5.3/gcc/include/QtGui/qmatrix4x4.h \
		../../Qt_off/5.3/gcc/include/QtGui/qvector4d.h \
		../../Qt_off/5.3/gcc/include/QtGui/qquaternion.h \
		../../Qt_off/5.3/gcc/include/QtGui/qgenericmatrix.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicswidget.h \
		../../Qt_off/5.3/gcc/include/QtGui/qfont.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicslayoutitem.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		../../Qt_off/5.3/gcc/include/QtGui/qevent.h \
		../../Qt_off/5.3/gcc/include/QtGui/qkeysequence.h \
		../../Qt_off/5.3/gcc/include/QtCore/qfile.h \
		../../Qt_off/5.3/gcc/include/QtCore/qfiledevice.h \
		../../Qt_off/5.3/gcc/include/QtGui/qvector2d.h \
		../../Qt_off/5.3/gcc/include/QtGui/qtouchdevice.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicsitem.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpixmap.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpaintdevice.h \
		../../Qt_off/5.3/gcc/include/QtGui/qcolor.h \
		../../Qt_off/5.3/gcc/include/QtGui/qrgb.h \
		../../Qt_off/5.3/gcc/include/QtGui/qimage.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpalette.h \
		../../Qt_off/5.3/gcc/include/QtGui/qbrush.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qaction.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qwidget.h \
		../../Qt_off/5.3/gcc/include/QtGui/qfontmetrics.h \
		../../Qt_off/5.3/gcc/include/QtGui/qfontinfo.h \
		../../Qt_off/5.3/gcc/include/QtGui/qcursor.h \
		../../Qt_off/5.3/gcc/include/QtGui/qicon.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qactiongroup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o canvas.o canvas.cpp

qtquick1applicationviewer.o: qtquick1applicationviewer/qtquick1applicationviewer.cpp qtquick1applicationviewer/qtquick1applicationviewer.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/QDeclarativeView \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeview.h \
		../../Qt_off/5.3/gcc/include/QtCore/qdatetime.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstring.h \
		../../Qt_off/5.3/gcc/include/QtCore/qchar.h \
		../../Qt_off/5.3/gcc/include/QtCore/qglobal.h \
		../../Qt_off/5.3/gcc/include/QtCore/qconfig.h \
		../../Qt_off/5.3/gcc/include/QtCore/qfeatures.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsystemdetection.h \
		../../Qt_off/5.3/gcc/include/QtCore/qprocessordetection.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt_off/5.3/gcc/include/QtCore/qtypeinfo.h \
		../../Qt_off/5.3/gcc/include/QtCore/qtypetraits.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsysinfo.h \
		../../Qt_off/5.3/gcc/include/QtCore/qlogging.h \
		../../Qt_off/5.3/gcc/include/QtCore/qflags.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qbasicatomic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt_off/5.3/gcc/include/QtCore/qgenericatomic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_mips.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_x86.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt_off/5.3/gcc/include/QtCore/qatomic_unix.h \
		../../Qt_off/5.3/gcc/include/QtCore/qglobalstatic.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmutex.h \
		../../Qt_off/5.3/gcc/include/QtCore/qnumeric.h \
		../../Qt_off/5.3/gcc/include/QtCore/qbytearray.h \
		../../Qt_off/5.3/gcc/include/QtCore/qrefcount.h \
		../../Qt_off/5.3/gcc/include/QtCore/qnamespace.h \
		../../Qt_off/5.3/gcc/include/QtCore/qarraydata.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstringbuilder.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsharedpointer.h \
		../../Qt_off/5.3/gcc/include/QtCore/qshareddata.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobject.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobjectdefs.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt_off/5.3/gcc/include/QtCore/qlist.h \
		../../Qt_off/5.3/gcc/include/QtCore/qalgorithms.h \
		../../Qt_off/5.3/gcc/include/QtCore/qiterator.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcoreevent.h \
		../../Qt_off/5.3/gcc/include/QtCore/qscopedpointer.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmetatype.h \
		../../Qt_off/5.3/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt_off/5.3/gcc/include/QtCore/qisenum.h \
		../../Qt_off/5.3/gcc/include/QtCore/qobject_impl.h \
		../../Qt_off/5.3/gcc/include/QtCore/qhash.h \
		../../Qt_off/5.3/gcc/include/QtCore/qpair.h \
		../../Qt_off/5.3/gcc/include/QtCore/qurl.h \
		../../Qt_off/5.3/gcc/include/QtCore/qurlquery.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstringlist.h \
		../../Qt_off/5.3/gcc/include/QtCore/qdatastream.h \
		../../Qt_off/5.3/gcc/include/QtCore/qiodevice.h \
		../../Qt_off/5.3/gcc/include/QtCore/qregexp.h \
		../../Qt_off/5.3/gcc/include/QtCore/qstringmatcher.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicssceneevent.h \
		../../Qt_off/5.3/gcc/include/QtCore/qpoint.h \
		../../Qt_off/5.3/gcc/include/QtCore/qrect.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmargins.h \
		../../Qt_off/5.3/gcc/include/QtCore/qsize.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpolygon.h \
		../../Qt_off/5.3/gcc/include/QtCore/qvector.h \
		../../Qt_off/5.3/gcc/include/QtCore/qset.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicsview.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpainter.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpixmap.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpaintdevice.h \
		../../Qt_off/5.3/gcc/include/QtGui/qwindowdefs.h \
		../../Qt_off/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		../../Qt_off/5.3/gcc/include/QtGui/qcolor.h \
		../../Qt_off/5.3/gcc/include/QtGui/qrgb.h \
		../../Qt_off/5.3/gcc/include/QtGui/qimage.h \
		../../Qt_off/5.3/gcc/include/QtGui/qtransform.h \
		../../Qt_off/5.3/gcc/include/QtGui/qmatrix.h \
		../../Qt_off/5.3/gcc/include/QtGui/qregion.h \
		../../Qt_off/5.3/gcc/include/QtCore/qline.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpainterpath.h \
		../../Qt_off/5.3/gcc/include/QtGui/qtextoption.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpen.h \
		../../Qt_off/5.3/gcc/include/QtGui/qbrush.h \
		../../Qt_off/5.3/gcc/include/QtGui/qfontinfo.h \
		../../Qt_off/5.3/gcc/include/QtGui/qfont.h \
		../../Qt_off/5.3/gcc/include/QtGui/qfontmetrics.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qscrollarea.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qabstractscrollarea.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qframe.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qwidget.h \
		../../Qt_off/5.3/gcc/include/QtGui/qpalette.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		../../Qt_off/5.3/gcc/include/QtGui/qcursor.h \
		../../Qt_off/5.3/gcc/include/QtGui/qkeysequence.h \
		../../Qt_off/5.3/gcc/include/QtGui/qevent.h \
		../../Qt_off/5.3/gcc/include/QtCore/qvariant.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmap.h \
		../../Qt_off/5.3/gcc/include/QtCore/qdebug.h \
		../../Qt_off/5.3/gcc/include/QtCore/qtextstream.h \
		../../Qt_off/5.3/gcc/include/QtCore/qlocale.h \
		../../Qt_off/5.3/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt_off/5.3/gcc/include/QtCore/qfile.h \
		../../Qt_off/5.3/gcc/include/QtCore/qfiledevice.h \
		../../Qt_off/5.3/gcc/include/QtGui/qvector2d.h \
		../../Qt_off/5.3/gcc/include/QtGui/qtouchdevice.h \
		../../Qt_off/5.3/gcc/include/QtWidgets/qgraphicsscene.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativedebug.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qtdeclarativeglobal.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/QDeclarativeComponent \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativecomponent.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarative.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeprivate.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeparserstatus.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativepropertyvaluesource.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativepropertyvalueinterceptor.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativelist.h \
		../../Qt_off/5.3/gcc/include/QtCore/qmetaobject.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeerror.h \
		../../Qt_off/5.3/gcc/include/QtScript/qscriptvalue.h \
		../../Qt_off/5.3/gcc/include/QtScript/qtscriptglobal.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/QDeclarativeEngine \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativeengine.h \
		../../Qt_off/5.3/gcc/include/QtDeclarative/QDeclarativeContext \
		../../Qt_off/5.3/gcc/include/QtDeclarative/qdeclarativecontext.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtquick1applicationviewer.o qtquick1applicationviewer/qtquick1applicationviewer.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_qtquick1applicationviewer.o: moc_qtquick1applicationviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtquick1applicationviewer.o moc_qtquick1applicationviewer.cpp

moc_canvas.o: moc_canvas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_canvas.o moc_canvas.cpp

moc_line.o: moc_line.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_line.o moc_line.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/demo1/bin || mkdir -p $(INSTALL_ROOT)/opt/demo1/bin
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/demo1/bin/$(QMAKE_TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/demo1/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/demo1/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

